[workspace]
members = ["color-wheel-lib", "color-wheel-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["James Thurley"]

[workspace.dependencies]
float-cmp = "0.9.0"
mockall = "0.11.3"
